# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartnet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smartnet.proto',
  package='smartnet',
  syntax='proto3',
  serialized_pb=_b('\n\x0esmartnet.proto\x12\x08smartnet\"\xe5\x01\n\tCommunity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x16\n\x0estreet_address\x18\x04 \x01(\t\x12\x0f\n\x07zipcode\x18\x05 \x01(\t\x12\x19\n\x11\x63reated_timestamp\x18\x06 \x01(\x03\x12\x10\n\x08place_id\x18\x07 \x01(\t\x12\x0b\n\x03lat\x18\x08 \x01(\t\x12\x0b\n\x03lon\x18\t \x01(\t\x12\x12\n\ncreated_by\x18\n \x01(\x05\x12\x0c\n\x04type\x18\x0b \x01(\x05\x12\r\n\x05state\x18\x0c \x01(\t\x12\x0f\n\x07\x63ountry\x18\r \x01(\t\"\x7f\n\x05\x41\x64min\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x14\n\x0cphone_number\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\x05\"!\n\x0f\x42ooleanResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"#\n\x0eIntegerRequest\x12\x11\n\trequestId\x18\x01 \x01(\x05\"V\n\x14\x43ommunityListRequest\x12\x0f\n\x07\x61\x64minId\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\x05\"7\n\rCommunityList\x12&\n\tcommunity\x18\x01 \x03(\x0b\x32\x13.smartnet.Community2\x99\x02\n\x08Smartnet\x12\x43\n\x0f\x63reateCommunity\x12\x13.smartnet.Community\x1a\x19.smartnet.BooleanResponse\"\x00\x12\x43\n\x10getCommunityById\x12\x18.smartnet.IntegerRequest\x1a\x13.smartnet.Community\"\x00\x12Q\n\x14getListOfCommunities\x12\x1e.smartnet.CommunityListRequest\x1a\x17.smartnet.CommunityList\"\x00\x12\x30\n\nadminLogin\x12\x0f.smartnet.Admin\x1a\x0f.smartnet.Admin\"\x00\x42\x13\n\x11\x63om.smartnet.grpcb\x06proto3')
)




_COMMUNITY = _descriptor.Descriptor(
  name='Community',
  full_name='smartnet.Community',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='smartnet.Community.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='smartnet.Community.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='smartnet.Community.city', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='street_address', full_name='smartnet.Community.street_address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zipcode', full_name='smartnet.Community.zipcode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_timestamp', full_name='smartnet.Community.created_timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='place_id', full_name='smartnet.Community.place_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='smartnet.Community.lat', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='smartnet.Community.lon', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='smartnet.Community.created_by', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='smartnet.Community.type', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='smartnet.Community.state', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='smartnet.Community.country', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=258,
)


_ADMIN = _descriptor.Descriptor(
  name='Admin',
  full_name='smartnet.Admin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='smartnet.Admin.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='smartnet.Admin.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='smartnet.Admin.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='smartnet.Admin.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='smartnet.Admin.email', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='smartnet.Admin.phone_number', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='smartnet.Admin.role', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=387,
)


_BOOLEANRESPONSE = _descriptor.Descriptor(
  name='BooleanResponse',
  full_name='smartnet.BooleanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='smartnet.BooleanResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=422,
)


_INTEGERREQUEST = _descriptor.Descriptor(
  name='IntegerRequest',
  full_name='smartnet.IntegerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='smartnet.IntegerRequest.requestId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=459,
)


_COMMUNITYLISTREQUEST = _descriptor.Descriptor(
  name='CommunityListRequest',
  full_name='smartnet.CommunityListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adminId', full_name='smartnet.CommunityListRequest.adminId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='smartnet.CommunityListRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='smartnet.CommunityListRequest.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='smartnet.CommunityListRequest.status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=547,
)


_COMMUNITYLIST = _descriptor.Descriptor(
  name='CommunityList',
  full_name='smartnet.CommunityList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='community', full_name='smartnet.CommunityList.community', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=604,
)

_COMMUNITYLIST.fields_by_name['community'].message_type = _COMMUNITY
DESCRIPTOR.message_types_by_name['Community'] = _COMMUNITY
DESCRIPTOR.message_types_by_name['Admin'] = _ADMIN
DESCRIPTOR.message_types_by_name['BooleanResponse'] = _BOOLEANRESPONSE
DESCRIPTOR.message_types_by_name['IntegerRequest'] = _INTEGERREQUEST
DESCRIPTOR.message_types_by_name['CommunityListRequest'] = _COMMUNITYLISTREQUEST
DESCRIPTOR.message_types_by_name['CommunityList'] = _COMMUNITYLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Community = _reflection.GeneratedProtocolMessageType('Community', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNITY,
  __module__ = 'smartnet_pb2'
  # @@protoc_insertion_point(class_scope:smartnet.Community)
  ))
_sym_db.RegisterMessage(Community)

Admin = _reflection.GeneratedProtocolMessageType('Admin', (_message.Message,), dict(
  DESCRIPTOR = _ADMIN,
  __module__ = 'smartnet_pb2'
  # @@protoc_insertion_point(class_scope:smartnet.Admin)
  ))
_sym_db.RegisterMessage(Admin)

BooleanResponse = _reflection.GeneratedProtocolMessageType('BooleanResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEANRESPONSE,
  __module__ = 'smartnet_pb2'
  # @@protoc_insertion_point(class_scope:smartnet.BooleanResponse)
  ))
_sym_db.RegisterMessage(BooleanResponse)

IntegerRequest = _reflection.GeneratedProtocolMessageType('IntegerRequest', (_message.Message,), dict(
  DESCRIPTOR = _INTEGERREQUEST,
  __module__ = 'smartnet_pb2'
  # @@protoc_insertion_point(class_scope:smartnet.IntegerRequest)
  ))
_sym_db.RegisterMessage(IntegerRequest)

CommunityListRequest = _reflection.GeneratedProtocolMessageType('CommunityListRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNITYLISTREQUEST,
  __module__ = 'smartnet_pb2'
  # @@protoc_insertion_point(class_scope:smartnet.CommunityListRequest)
  ))
_sym_db.RegisterMessage(CommunityListRequest)

CommunityList = _reflection.GeneratedProtocolMessageType('CommunityList', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNITYLIST,
  __module__ = 'smartnet_pb2'
  # @@protoc_insertion_point(class_scope:smartnet.CommunityList)
  ))
_sym_db.RegisterMessage(CommunityList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.smartnet.grpc'))

_SMARTNET = _descriptor.ServiceDescriptor(
  name='Smartnet',
  full_name='smartnet.Smartnet',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=607,
  serialized_end=888,
  methods=[
  _descriptor.MethodDescriptor(
    name='createCommunity',
    full_name='smartnet.Smartnet.createCommunity',
    index=0,
    containing_service=None,
    input_type=_COMMUNITY,
    output_type=_BOOLEANRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getCommunityById',
    full_name='smartnet.Smartnet.getCommunityById',
    index=1,
    containing_service=None,
    input_type=_INTEGERREQUEST,
    output_type=_COMMUNITY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getListOfCommunities',
    full_name='smartnet.Smartnet.getListOfCommunities',
    index=2,
    containing_service=None,
    input_type=_COMMUNITYLISTREQUEST,
    output_type=_COMMUNITYLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='adminLogin',
    full_name='smartnet.Smartnet.adminLogin',
    index=3,
    containing_service=None,
    input_type=_ADMIN,
    output_type=_ADMIN,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMARTNET)

DESCRIPTOR.services_by_name['Smartnet'] = _SMARTNET

# @@protoc_insertion_point(module_scope)
